DROP TABLE restaurants CASCADE;
DROP TABLE reviews CASCADE;
DROP TABLE review_categories CASCADE;
DROP TABLE grades CASCADE;
DROP TABLE addresses CASCADE;
DROP TABLE streets CASCADE;
DROP TABLE cities CASCADE;
DROP TABLE users CASCADE;
